"""
Simple 2D slice dataloader for AMOS, reads pre-processed PNG files generated by preprocess.py.

Layout expected (created by preprocess.py):
    <preproc_root>/Tr/images/amos_0007_slice023.png   (RGB, 256x256, uint8)
    <preproc_root>/Tr/labels/amos_0007_slice023.png   (L,   256x256, uint8 class indices 0..15)
    <preproc_root>/Tr/manifest.json                   {case_id: [slice_idx, ...]}

Splits (which case IDs go to train vs val) come from nnU-Net's splits_final.json so the
baseline cross-validation matches the user's nnU-Net training. We then expand each case
into all of its foreground slices via the manifest.

Augmentations are classic Albumentations (HFlip / VFlip / rotations / intensity tweaks).
Normalization is ImageNet mean/std on the [0,1] PNG range — standard practice for any
ImageNet-pretrained backbone.
"""

import os
import json
from pathlib import Path
from typing import List, Sequence

import numpy as np
import torch
from torch.utils.data import Dataset
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2


# ImageNet normalization — the standard for any model pretrained on ImageNet.
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)


# ------------------------------------------------------------------------------
# Splits utilities
# ------------------------------------------------------------------------------
def load_splits(splits_json: str, fold: int):
    with open(splits_json) as f:
        splits = json.load(f)
    assert 0 <= fold < len(splits), f"Fold {fold} out of range (file has {len(splits)} folds)."
    return list(splits[fold]['train']), list(splits[fold]['val'])


def expand_cases_to_slices(case_ids: Sequence[str], manifest: dict) -> List[str]:
    """Turn ['amos_0007', ...] into ['amos_0007_slice023', 'amos_0007_slice024', ...]"""
    out = []
    missing = []
    for cid in case_ids:
        if cid not in manifest:
            missing.append(cid)
            continue
        for si in manifest[cid]:
            out.append(f"{cid}_slice{si:03d}")
    if missing:
        print(f"[warn] {len(missing)} case(s) requested but not in preprocessing manifest: "
              f"{missing[:5]}{'...' if len(missing) > 5 else ''}")
    return out


# ------------------------------------------------------------------------------
# Augmentation pipelines
# ------------------------------------------------------------------------------
def build_train_transform(image_size: int = 256):
    """Classic 2D segmentation augmentations: flips + rotation + mild intensity jitter."""
    return A.Compose([
        A.Resize(image_size, image_size),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.Rotate(limit=30, p=0.5, border_mode=0),
        A.RandomBrightnessContrast(brightness_limit=0.15, contrast_limit=0.15, p=0.5),
        A.GaussianBlur(blur_limit=(3, 5), p=0.2),
        A.GaussNoise(var_limit=(5.0, 20.0), p=0.2),
        A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ToTensorV2(),
    ])


def build_val_transform(image_size: int = 256):
    """No augmentation — just resize + ImageNet normalization."""
    return A.Compose([
        A.Resize(image_size, image_size),
        A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ToTensorV2(),
    ])


# ------------------------------------------------------------------------------
# Dataset
# ------------------------------------------------------------------------------
class AMOS2DPNGDataset(Dataset):
    """
    A flat list of 2D PNG slices. Each __getitem__ returns:
        image: (3, H, W) float tensor, ImageNet-normalized
        label: (H, W)    long tensor with class indices 0..15
        sample_id: str   like "amos_0007_slice023"
    """

    def __init__(self,
                 preproc_split_dir: str,
                 sample_ids: Sequence[str],
                 transform=None):
        """
        preproc_split_dir: path like ".../preprocessed_2d/Tr"
        sample_ids:        list of "amos_<id>_slice<NNN>" strings (from expand_cases_to_slices)
        transform:         an Albumentations transform; if None, build_val_transform() is used.
        """
        self.images_dir = Path(preproc_split_dir) / "images"
        self.labels_dir = Path(preproc_split_dir) / "labels"
        self.sample_ids = list(sample_ids)
        self.transform = transform if transform is not None else build_val_transform()

    def __len__(self) -> int:
        return len(self.sample_ids)

    def __getitem__(self, idx):
        sid = self.sample_ids[idx]
        img = np.array(Image.open(self.images_dir / f"{sid}.png").convert('RGB'))   # (H, W, 3) uint8
        lbl = np.array(Image.open(self.labels_dir / f"{sid}.png"))                  # (H, W)    uint8

        out = self.transform(image=img, mask=lbl)
        image = out['image']                          # (3, H, W) float, ImageNet-normalized
        label = out['mask'].long()                    # (H, W) long
        return image, label, sid
